homeassistant:
  customize: !include_dir_merge_named ../customizations/entities
  allowlist_external_dirs:
    - /mnt/rpicam
    - /home/homeassistant/test
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
          #      allow_bypass_login: true
    - type: legacy_api_password
      api_password: !secret home_pass
