- id: '1608050471763'
  alias: test blueprint
  description: ''
  use_blueprint:
    path: simple_double_click.yaml
    input:
      switch_id:
        entity_id: switch.s_bureau
      long_click_action:
      - service: light.turn_on
        data: {}
        entity_id: light.l_bureau
      short_click_action:
      - service: light.turn_off
        data: {}
        entity_id: light.l_bureau
- id: '1608064173080'
  alias: Short long double click
  description: ''
  use_blueprint:
    path: clicks.yaml
    input:
      switch_id: switch.s_bureau
      long_click_action: []
      short_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_salon_plafond
      double_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_cuisine_plafond
      delay: '0.3'
- id: '1608232681550'
  alias: test 1712
  description: ''
  use_blueprint:
    path: clicks.yaml
    input:
      switch_id: switch.s_bureau
      long_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_salon_plafond
      short_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_sam_plafond
      double_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_hall_plafond
      delay: '0.5'
- id: '1608234267331'
  alias: Short long double click binary
  description: ''
  use_blueprint:
    path: slashback/trigger-different-actions-on-a-single-double-or-double-click-on-a-binary-sensor.yaml
    input:
      delay: '0.5'
      switch_id: binary_sensor.1tpx439_liquid_range_critical
      long_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_salon_plafond
      short_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_sam_plafond
      double_click_action:
      - service: light.toggle
        data: {}
        entity_id: light.l_hall_plafond
