blueprint:
    name: Short long double click
    description: Differnet Actions on Short, Long and Double switch click
    domain: automation
    input:
        switch_id:
            name: Switch or Binary sensor entity
            description: The switch or binary_sensor use to trigger the automation
            selector:
                entity:
                    domain: switch
        long_click_action:
            name: Long click action
            description: The action(s) to launch for a long click
            default: []
            selector: 
                action:
        short_click_action:
            name: Short click action
            description: The action(s) to launch for a single short click
            default: []
            selector: 
                action:
        double_click_action:
            name: Double click action
            description: The action(s) to launch for a double click
            default: []
            selector: 
                action:
        delay:
            name: Delay in seconds
            description: The time in seconds (can contain decimals) used as a delay for the double or long click detection
            default: 0.3
            selector:
                number:
                    min: 0.0
                    max: 10.0
                    unit_of_measurement: seconds
trigger:
  - platform: state
    entity_id: !input switch_id
    to: 'on'
action:
  - variables:
        switch_id: !input switch_id
  - wait_template: "{{ is_state(switch_id, 'off') }}"
    timeout: !input delay
    continue_on_timeout: true
  - choose:
      - conditions: "{{ not wait.completed }}" # long click
        sequence: !input long_click_action
    default:  
      - wait_template: "{{ is_state(switch_id, 'on') }}" # second click?
        timeout: !input delay
        continue_on_timeout: true
      - choose:
          - conditions: "{{ not wait.completed }}" #single click
            sequence: !input short_click_action
        default: !input double_click_action  # double click
