blueprint:
    name: Short long click
    description: Short and Long switch click
    domain: automation
    input:
        switch_id:
            selector:
                entity:
                    domain: binary_sensor
        long_click_action:
            default: []
            selector: 
                action:
        short_click_action:
            default: []
            selector: 
                action:
trigger:
  - platform: state
    entity_id: !input switch_id
    to: 'on'
action:
  - variables:
        switch_id: !input switch_id
  - wait_template: "{{ is_state(switch_id, 'off') }}"
    timeout: 0.3
    continue_on_timeout: true
  - choose:
      - conditions: "{{ not wait.completed }}"
        sequence: !input long_click_action
    default: !input short_click_action
